name: Build_release
on:
  push:
    tags:
      - "rc-0.0.*"
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
          cache: "npm"

      #- name: npm ci
      #  run: npm ci

      #- name: Check ts
      #  run: npm run ts

      #- name: Check linter
      #  run: npm run lint

      #- name: Test
      #  run: npm run test

      #- name: build
      #  run: npm run build
      - name: install fetch
        run: |
          cd .github/workflows/scripts
          npm install node-fetch
          npm i @actions/exec
      - name: ticket info
        env:
          TOKEN: ${{ secrets.TOKEN_YANDEX_TRACKER }}
          ORGID: ${{ secrets.ID_ORG }}
          ACTOR: ${{ github.actor }}
          TAG: ${{ github.ref_name }}
        run: node .github/workflows/scripts/ticketFill.js
