name: Build_release
on:
push:
  tags:
    - "rc-*.*.*"
jobs:
  build_release:
    on:
    push:
      tags:
        - "rc-*.*.*"
    runs-on: ubuntu-latest
    needs: [checking]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
          cache: "npm"

      - name: npm ci
        run: npm ci

      - name: Check ts
        run: npm run ts

      - name: Check linter
        run: npm run lint

      - name: Test
        run: npm run test

      - name: build
        run: npm run build

      - name: post
        env:
          TOKEN: ${{ secrets.TOKEN_YANDEX_TRACKER }}
          ORGID: ${{ secrets.ID_ORG }}
        uses: satak/webrequest-action@v1.2.4
        with:
          url: https://api.tracker.yandex.net/v2/issues/HOMEWORKSHRI-143
          method: PATCH
          payload: '{"summary": "Кросс-проверка Инфраструктура — Васин Максим", "description": "Описание из экшанов с секретом"}'
          headers: '{"Authorization": "OAuth ${{ env.TOKEN }}", "X-Org-ID": "${{ env.ORGID }}"}'
