name: Checking_ts_linter
env: 
  CAN_BUILD: true;
  TAG_NAME: A;
#  GIT_VAR    : "im git var ${{ github.sha }}"
on: [push]
jobs:
  checking:
    runs-on: ubuntu-latest
    steps:
    
    - name: install nvm
      run: |
        sudo apt install curl
        curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
        source ~/.bashrc
        node -v
        npm install -g typescript
      
    - name: Git clone
      uses: actions/checkout@v1
      
    - name: nmp i
      run: npm i
      
    - name: Check ts
      run: npm run ts
    
    - name: Check linter
      run: npm run lint
      #  nvm install 16.16.0
      
    #- name: Get tag
      #run: |
        #git tag -l
        #echo $?
        
        #- uses: actions-ecosystem/action-get-latest-tag@v1
        #id: get-latest-tag
    - name: Can Build
      if: ${{ env.CAN_BUILD }}
      run: echo "$CAN_BUILD"
      
  build_release:
    if: ${{ github.ref != '' }}
    runs-on: ubuntu-latest
    needs: [checking]
    steps:
    #- name: build
      #run: npm run build
    - name: try create docker
      run: echo 'AAA'
    - name: post
      uses: satak/webrequest-action@v1.2.4
      with:
        url: https://api.tracker.yandex.net/v2/issues/HOMEWORKSHRI-143
        method: PATCH
        payload: '{"summary": "Кросс-проверка Инфраструктура — Васин Максим", "description": "Описание из экшанов"}'
        headers: '{"Authorization": "OAuth y0_AgAAAAANPDNaAAiGogAAAADSOoNbmLy5EvCuSOugQ7c9_wH_LdbgQZQ", "X-Org-ID": "7526988"}'
