name: Checking_ts_linter
#run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
#env:
#  MY_VARIABLE: "im Variable"
#  GIT_VAR    : "im git var ${{ github.sha }}"
on: [push]
jobs:
  checking_ts:
    runs-on: ubuntu-latest
    steps:
      
    - name: Git clone
      uses: actions/checkout@v1
      
    - name: install nvm
      run: |
        sudo apt install curl
        curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
      
    - name: show folder
      run: ls -la | grep .ts
